# Generated by Django 3.2.6 on 2021-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='loggedin',
            field=models.TextField(default='False'),
        ),
    ]
